name: ci

on:
  push:
    tags:
      - "v*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build a fully statically linked program
        run: docker run --rm -v $(pwd):/workspace -w /workspace crystallang/crystal:latest-alpine make build-static && cp bin/difftance difftance-x86_64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            difftance-x86_64
