name: release

on:
  push:
    tags:
      - "v*.*"

jobs:
  release-linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2

      - name: Build a fully statically linked program
        run: make build-static && cp bin/difftance difftance-linux-x86_64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            difftance-linux-x86_64
            LICENSE
