name: release

on:
  push:
    tags:
      - "v*.*"

jobs:
  release-linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3

      - name: Build a fully statically linked program
        run: make build-static && cp bin/difftance difftance-linux-x86_64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            difftance-linux-x86_64
            LICENSE

  release-windows:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF instead of CRLF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - name: Build
        shell: bash
        run: |
          shards build --release --no-debug
          mv bin/difftance.exe difftance.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: difftance.exe
