name: test

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - name: Run tests
        run: crystal spec

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF instead of CRLF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - name: Build
        run: |
          shards build --release --no-debug
          strip bin/difftance.exe
          7z a difftance.zip bin/difftance.exe
      - uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: difftance.zip
